= Pflichtenheft Leonie
// Metadata
Sebastian Scholl <scholl.sebastian@gmx.at>
1.0, 20-01-2020

// Settings
:source-highlighter: coderay
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: src/main/java/at/htl/jdbcprimer
:sourcedir-test: src/test/java/at/htl/jdbcprimer
:toc:

Version: {revnumber} +
Version Date: {revdate} +
Version Notes: Erster Vorschlag +
Author: {Author} {email}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++


== Beschreibung der Ausgangssituation

Leonie ist ein künstlich intelligenter Sprachassistent. Sie kann auf bestimmte definierte Fragen definierte Antworten geben oder im Internet nach einer Antwort suchen

== Istzustand

Leonie kann bis jetzt nur vordefinierte Antworten geben. Wenn Leonie keine Antwort auf eine Frage hat, sucht sie im Internet nach einer Antwort.

=== Beschreibung der Geschäftsprozesse

* Auftritte auf diversen Events
** z.B.: OÖ. Zukunftssymposium 2019, Neujahrsveranstaltung der Stadt Leonding
* Humanisierung von Leonie
** Das Reden mit Leonie soll nicht mehr so wirken, als rede man mit einem Roboter
* Ambilight und Gefühle
** Leonie soll beispielsweise wenn sie keine Antwort auf eine Frage hat, traurig sein und ihre Gefühle im 3D Modell darstellen. Darüber hinaus soll sich die Beleuchtung der Box dementsprechend ändern.

== Problemstellung

Wenn Gäste die Schule besuchen, finden sie oft den richtigen Raum des gesuchten Professors nicht. Außerdem wirkt Leonie nicht sehr "menschlich", wenn man mit ihr spricht.

== Aufgabenstellung

Wenn Gäste die Schule besuchen, finden sie oft den richtigen Raum des gesuchten Professors nicht. Außerdem wirkt Leonie nicht sehr "menschlich", wenn man mit ihr spricht.

=== Funktionale Anforderungen

==== Anwendungsfalldiagramm (Use-Case-Diagram)

[plantuml]
----
left to right direction
actor User
actor ChatBot
actor nodeBackend
actor LeonieHolo
actor FaceRecognition
actor LeonieWeb
actor MQTTServer
actor Ambilight

rectangle Leonie {
    User -- (stelle Frage)
    FaceRecognition -- (erkenne Gesicht)
    ChatBot -- (erkenne Intention)
    nodeBackend -- (suche Antwort)
    LeonieHolo -- (stelle Leonie in 3D dar)
    LeonieWeb -- (zeige Spracheingabe an)
    LeonieWeb -- (schicke die Spracheingabe zum Backend)
    LeonieWeb -- (gib die Antwort aus)
    MQTTServer -- (vernetze die einzelnen Komponenten)
    Ambilight -- (stelle Gefühle farblich dar)
}
----

==== Use-Case 1

===== Charakterisierende Informationen Use-Case 1

[cols=2]
|===
| Übergeordneter elementarer Geschäftsprozess:
| Prozess-ID: <elementarer Geschäftsprozess (verweist auf Abschnitt „2.1.5 Beschreibung der Geschäftsprozesse“)>

| Ziel des Use Cases:
| <Ausführliche Beschreibung des Zieles des Use Cases>

| Umgebende Systemgrenze:
| <System, das betrachtet wird (Systemgrenze im Diagramm des vorigen Abschnittes)>

| Vorbedingung:
| <Was muss garantiert werden, damit der Use Case durchgeführt werden kann?>

| Nachbedingung bei erfolgreicher Ausführung:
| <Was muss sichergestellt werden für eine erfolgreiche Ausführung des Use Case>

| Beschreibung:
a|
* Erste Aktion
* Zweite Aktion
* ...

| Beteiligte Nutzer:
| <Rollenname>: Beschreibung des Nutzers, der mit dem System interagiert. Nutzer können auch andere Systeme sein.>

| Auslösendes Ereignis:
| <Handlung oder Zeitpunkt, die Use Case auslöst bzw. zu dem er beginnt>
|===

===== GUI für den Aufruf des Use-Case 1

==== Use-Case 2

...

TIP: Dieser Abschnitt muß als Template für jeden Use Case aus dem vorigen Abschnitt wiederholt werden.

=== Nicht-funktionale Anforderungen

Typen von Produktcharakteristiken

Typ USE: 		Benutzbarkeitsanforderung

Die in Abschnitt 1 beschriebene Zielgruppe liegt diesen Anforderungen zugrunde. Wie muß die Software beschaffen sein, damit diese Zielgruppe gerne damit arbeitet?
Beispiel: Die Software soll flexibel für unterschiedliche Arbeitsweisen einsetzbar sein.
ODER
Die Software soll dem Erscheinungsbild anderer Produkte des Herstellers
entsprechen.

Typ EFFIZIENZ: 	Effizienzanforderung

Hier geht es sowohl um Laufzeit- als auch um Speichereffizienz. Was wird unter dem sparsamen Einsatz dieser Ressourcen verstanden?
Beispiel: Die Berechnung darf nicht länger als 0,25 Sekunden dauern.

Typ PFLEGE:	Wartbarkeits- und Portierbarkeitsanforderung

Welcher Grad an Änderbarkeit wird gefordert? Hier werden, soweit wie möglich, kommende Anpassungen und Erweiterungen vorhergesehen.
Beispiel: Das Produkt soll später auch in englischer Sprache verfügbar sein.

Typ SICHER:	Sicherheitsanforderung

Zu den Sicherheitsanforderungen gehören die Aspekte Vertraulichkeit, Datenintegrität und Verfügbarkeit. Wie sehr müssen die Daten vor dem Zugriff durch Dritte geschützt werden? Ist es entscheidend, die Korrektheit der erfassten Daten und ihre Konsistenz zu gewährleisten? Dürfen Systemausfälle vorkommen?
Beispiel: Das System muss gewährleisten, dass Daten nie verändert werden können.

Typ LEGAL:		Gesetzliche Anforderung
Welche Standards und Gesetze müssen beachtet werden?
Beispiel: Das Produkt muss die ISO 9000 Norm erfüllen.

== Zielsetzung

Leonie soll externen Besuchern Wegbeschreibungen zu den Räumen der Lehrer geben. Außerdem soll Leonie "menschlicher" wirken, wenn man mit ihr redet.
